// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosAspNetCore5.Models;

namespace PedidosAspNetCore5.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20210614151629_CriacaoTabelas")]
    partial class CriacaoTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PedidosAspNetCore5.Models.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeContato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedores");

                    b.HasData(
                        new
                        {
                            FornecedorId = 1,
                            CNPJ = "04386272000122",
                            EmailContato = "administracao@franciscoeoliverentulhosltda.com.br",
                            NomeContato = "Oliver",
                            RazaoSocial = "Francisco e Oliver Entulhos Ltda",
                            UF = "CE"
                        },
                        new
                        {
                            FornecedorId = 2,
                            CNPJ = "29783701000126",
                            EmailContato = "estoque@josefaefabioadvocaciame.com.br",
                            NomeContato = "Josefa",
                            RazaoSocial = "Josefa e Fábio Advocacia ME",
                            UF = "CE"
                        },
                        new
                        {
                            FornecedorId = 3,
                            CNPJ = "62777062000161",
                            EmailContato = "contato@mirellaecalebevidrosme.com.br",
                            NomeContato = "Mirella",
                            RazaoSocial = "Mirella e Calebe Vidros ME",
                            UF = "CE"
                        },
                        new
                        {
                            FornecedorId = 4,
                            CNPJ = "00956073000151",
                            EmailContato = "contabil@julioeosvaldoesportesltda.com.br",
                            NomeContato = "Julio",
                            RazaoSocial = "Julio e Osvaldo Esportes Ltda",
                            UF = "CE"
                        });
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("QtdItem")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            PedidoId = 1,
                            DataCadastro = "14/06/2021",
                            FornecedorId = 1,
                            QtdItem = 2,
                            Valor = 10.98m
                        },
                        new
                        {
                            PedidoId = 2,
                            DataCadastro = "14/06/2021",
                            FornecedorId = 1,
                            QtdItem = 1,
                            Valor = 4.99m
                        });
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.PedidoItem", b =>
                {
                    b.Property<int>("PedidoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("PedidoItemId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoItens");

                    b.HasData(
                        new
                        {
                            PedidoItemId = 1,
                            PedidoId = 1,
                            PrecoUnitario = 4.99m,
                            ProdutoId = 2
                        },
                        new
                        {
                            PedidoItemId = 2,
                            PedidoId = 1,
                            PrecoUnitario = 5.99m,
                            ProdutoId = 1
                        },
                        new
                        {
                            PedidoItemId = 3,
                            PedidoId = 2,
                            PrecoUnitario = 4.99m,
                            ProdutoId = 2
                        });
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataCadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            DataCadastro = "14/06/2021",
                            Descricao = "Maça",
                            Preco = 5.99m
                        },
                        new
                        {
                            ProdutoId = 2,
                            DataCadastro = "14/06/2021",
                            Descricao = "Banana",
                            Preco = 4.99m
                        },
                        new
                        {
                            ProdutoId = 3,
                            DataCadastro = "14/06/2021",
                            Descricao = "Melão",
                            Preco = 5.99m
                        },
                        new
                        {
                            ProdutoId = 4,
                            DataCadastro = "14/06/2021",
                            Descricao = "Laranja",
                            Preco = 8.99m
                        });
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Pedido", b =>
                {
                    b.HasOne("PedidosAspNetCore5.Models.Fornecedor", "Fornecedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.PedidoItem", b =>
                {
                    b.HasOne("PedidosAspNetCore5.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedidosAspNetCore5.Models.Produto", "Produto")
                        .WithMany("PedidoItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Fornecedor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PedidosAspNetCore5.Models.Produto", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
